mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    # path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('polls.urls', namespace='')), #временное решение, чтобы не заполнять лишними запросами
]

# id in DEBUG mode server doesnt cache static urls
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path;

from . import views;


app_name = 'polls';
urlpatterns = [
    # main page (all questions)
    path('', views.IndexView.as_view(), name='index'),
    
    # user
    path('account/login/', views.PLoginView.as_view(), name='login'),
    path('accout/profile/delete/', views.PDeleteUserView.as_view(), name="profile_delete"),
    path('account/profile/change_password/', views.PPasswordChangeView.as_view(), name='password_change'),
    path('account/profile/change/', views.PChangeUserInfoView.as_view(), name='profile_change'),
    path('account/profile/', views.p_profile, name='profile'),
    path('account/register/', views.PRegisterUserView.as_view(), name='register'),
    path('account/register/done/', views.PRegisterDoneView.as_view(), name='register_done'),
    path('account/logout/', views.p_logout, name='logout'),
    
    
    
    # question
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('question_create/', views.question_create, name='question_create'),
    path('<int:question_id>/question_delete/', views.question_delete, name='question_delete'),
    
];

mysite/polls/models.py
import datetime;

from django.db import models;
from django.utils import timezone;
from django.contrib.auth.models import AbstractUser;
from datetime import date

from .utilities import get_timestamp_path


class PUser(AbstractUser):
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Аватар', default='default_avatar.jpg');
    
    def delete(self, *args, **kwargs):
        for qu in self.question_set.all():
            qu.delete()
        super().delete(*args, **kwargs)
    
    class Meta(AbstractUser.Meta):
        pass;

class Question(models.Model):
    question_header = models.CharField(max_length=100, verbose_name='Заголовок');
    question_text = models.CharField(max_length=200, verbose_name='Вопрос');
    pub_date = models.DateTimeField('date published', default=date.today);
    death_date = models.DateField('date death');
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение');
    author = models.ForeignKey(PUser, on_delete=models.CASCADE, verbose_name='Автор вопроса');
    can_reanswer = models.BooleanField(verbose_name="Можно заново переголосовать")
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1);

    def __str__(self):
        return self.question_text;

    def delete(self, *args, **kwargs):
        for ch in self.choice_set.all():
            ch.delete()
        super().delete(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Опросы'
        verbose_name = 'Опрос'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE);
    choice_text = models.CharField(max_length=200);
    votes = models.IntegerField(default=0);

    def __str__(self):
        return self.choice_text;

class UserChoice(models.Model):
    user = models.ForeignKey(PUser, on_delete=models.CASCADE);
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE);
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    def delete(self, *args, **kwargs):
        ch = UserChoice.objects.get(choice=self.choice).count();
        ch.votes -= 1;
        ch.save();
        super().delete(*args, **kwargs)

mysite/polls/forms.py
from django.contrib.auth import password_validation;
from django.core.exceptions import ValidationError;
# from .models import user_registrated;
from django.contrib.auth import authenticate, login;
from django.forms import inlineformset_factory

from django.utils.translation import gettext_lazy;
from .models import PUser, Question, Choice;
from django import forms;

#FORMS

class FormChangeUserInfo(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес эл. почты');
    image = forms.ImageField(required=False, label="Аватар пользователя");
    class Meta:
        model = PUser;
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'image',
        );

class FormRegisterUser(forms.ModelForm):
    email = forms.EmailField(required = True,
                             label = "Адрес электронной почты");
    password1 = forms.CharField(label= 'Пароль',
                                widget=forms.PasswordInput,
                                help_text= password_validation.password_validators_help_text_html());
    password2 = forms.CharField(label='Подтвердить пароль',
                                widget=forms.PasswordInput,
                                help_text="Повторите пароль пожалуйста.");
    def clean_password(self):
        password1 = self.cleaned_data["password1"];
        if password1:
            password_validation.validate_password(password1);
        return password1;

    def clean(self):
        super().clean();
        password1 = self.cleaned_data["password1"];
        password2 = self.cleaned_data["password2"];
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError
            ('Введенные пароли не совпадают', code='password_mismatch')};
            raise ValidationError(errors);

    def save(self, commit=True):
        user = super().save(commit=False);
        user.set_password(self.cleaned_data["password1"]);
        if commit:
            user.save();
        # user_registrated.send(FormRegisterUser, instance=user);
        return user;

    class Meta:
        model = PUser;
        fields = ('username', 'email', 'first_name', 'last_name',
                'password1', 'password2');

class FormQuestion(forms.ModelForm):
    death_date = forms.DateTimeField(label='Время окончания опроса', widget=forms.SelectDateWidget, help_text='Выберите дату, когда опрос перестанет быть действительным')
    class Meta:
        model = Question;
        fields = ('author', 'question_header', 'question_text', 'image', 'death_date');
        widgets = {'author': forms.HiddenInput};

FormChoiceSet = inlineformset_factory(Question, Choice, fields=('choice_text',), extra=4,)

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect;
from django.http import HttpResponse, HttpResponseRedirect;
from .models import Question, Choice, PUser;
from django.template import loader;
from django.urls import reverse, reverse_lazy;
from django.views import generic;
from django.views.generic import UpdateView, CreateView, DeleteView;

from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist

from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth import logout, authenticate, login;
from django.contrib.auth.decorators import login_required;
from django.contrib.auth.mixins import LoginRequiredMixin;
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin;

from .forms import FormChangeUserInfo, FormRegisterUser, FormQuestion, FormChoiceSet;
from .models import PUser, UserChoice;

# QUESTIONS

class IndexView(generic.ListView):
    template_name = 'polls/question/index.html';
    context_object_name = 'latest_question_list';

    # return all questions sorted by date
    def get_queryset(self):
        return Question.objects.order_by('-pub_date');


class DetailView(generic.DetailView):
    model = Question;
    template_name = 'polls/question/detail.html';


class ResultsView(generic.DetailView):
    model = Question;
    template_name = 'polls/question/results.html';


@login_required(login_url="polls:login")
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id);
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice']);
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/question/detail.html', {
            'question': question,
            'error_message': 'вы не сделали выбор'
        });
    try:
        user_choice = UserChoice.objects.get(question=question_id, user=request.user.pk);
        choices = [user_choice.choice.pk, selected_choice.pk]
        user_choice.choice = selected_choice; 
        user_choice.save();
        
        choice = Choice.objects.get(pk=choices[0]);
        choice.votes -= 1
        choice.save();
        
        choice = Choice.objects.get(pk=choices[1]);
        choice.votes += 1
        choice.save();
    # if get more than one answer (debug)
    except ObjectDoesNotExist:
        UserChoice(user=request.user, choice=selected_choice, question=Question.objects.get(pk=question_id)).save();
        user_choice = UserChoice.objects.get(user=request.user, choice=selected_choice, question=Question.objects.get(pk=question_id))
        choice = Choice.objects.get(pk=user_choice.choice.pk);
        choice.votes += 1;
        choice.save();
    # UserChoice.objects.all().delete();
    for choices in Choice.objects.filter(question_id=question_id):
        choices.votes = UserChoice.objects.filter(choice=choices).count();
        choices.save();
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)));

@login_required(login_url="polls:login")
def question_create(request):
    if request.method == 'POST':
        form = FormQuestion(request.POST, request.FILES);
        if form.is_valid():
            question = form.save();
            formset = FormChoiceSet(request.POST, instance=question);
            if formset.is_valid():
                formset.save();
                messages.add_message(request, messages.SUCCESS, 'Опрос добавлен');
                return redirect('polls:profile');
    else:
        form = FormQuestion(initial={'author': request.user.pk});
        formset = FormChoiceSet();
    context = {'form': form, 'formset':formset};
    return render(request, 'polls/question/create.html',context);

@login_required(login_url="polls:login")
def question_delete(request, question_id):
    try:
        Question.objects.get(author=request.user.pk, pk=question_id).delete();
        messages.add_message(request, messages.SUCCESS, "Вопрос удален!");
        return redirect('polls:profile')
    except:
        messages.add_message(request, messages.SUCCESS, "Вопрос не удалось удалить!");
        
        return redirect('polls:profile')

    
        


# USER VIEWS

class PLoginView(LoginView):
    template_name = 'polls/user/login.html';
    next_page = 'polls:profile';

@login_required(login_url="polls:login")
def p_profile(request):
    questions = Question.objects.filter(author=request.user.pk);
    context = {"questions": questions};
    return render(request, "polls/user/profile.html", context);

@login_required(login_url="polls:login")
def p_profile_change(request):
    pass;

@login_required(login_url="polls:login")
def p_logout(request):
    logout(request);
    return redirect('/');

class PChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = PUser;
    template_name = 'polls/user/profile_change.html';
    form_class = FormChangeUserInfo;
    success_url = reverse_lazy('polls:profile');
    success_message = 'Личные данные полльзователя изменены';
    login_url = reverse_lazy('polls:login')


    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk;
        return super().dispatch(request, *args, **kwargs);
    
    def get_object(self, queryset = None):
        if not queryset:
            queryset = self.get_queryset();
        return get_object_or_404(queryset, pk=self.user_id);

class PPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'polls/user/password_change.html';
    success_url = reverse_lazy('polls:profile');
    success_message = 'Пароль изменен';
    login_url = reverse_lazy('polls:login')


class PRegisterDoneView(generic.base.TemplateView, LoginRequiredMixin):
    template_name = 'polls/user/register_user_success.html';
    login_url = reverse_lazy('polls:login')


class PRegisterUserView(CreateView):
    model = PUser;
    template_name = 'polls/user/register_user.html';
    form_class = FormRegisterUser;
    success_url = reverse_lazy('polls:register_done');
    
    # перепись сценария при регистрации пользователя
    
    def form_valid(self, form):
        # вызываем метод для сохранения пользователя с данными из формы
        user = form.save();
        """
        вызов родительского метода (сразу после сохранения), чтобы
        CreateView отработал.
        """
        response = super().form_valid(form);
        user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password1"]);
        # чтобы избежать ошибки в случае, если не удастся войти
        if user is not None:
            login(self.request, user);
        return response;
    
class PDeleteUserView(LoginRequiredMixin, DeleteView):
    model = PUser;
    template_name = 'polls/user/profile_delete.html'
    success_url = reverse_lazy('polls:index')
    login_url = reverse_lazy('polls:login')
    
    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, "Пользователь удален")
        return super().post(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

mysite/polls/templates/polls/user/login.html
{% extends "layout/basic.html" %}
{% block title %} Вход {% endblock %}
{% block content %}
    <h2>Вход</h2>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход.</p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{form}}
            <input type="hidden" name="next" value="{{ next }}">
            <button class="a-button" type="submit" name="submit">Завершить</button>
        </form>
    {% endif %}
{% endblock %}

mysite/polls/templates/polls/user/password_change.html
{% extends "layout/basic.html" %}
{% block title %} Правка личных данных {% endblock %}
{% block content %}
    <h2>Изменение пароля {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="a-button" type="submit" name="submit">Завершить</button>
    </form>
{% endblock %}

mysite/polls/templates/polls/user/profile.html
{% extends "layout/basic.html" %}
{% load thumbnail %}
{% load static %}
{% block title %} Профиль пользователя {% endblock %}
{% block content %}
<div class="split-box profile">
    <div>
        <h2>Профиль пользователя {{ user.username }}</h2>
        {% if user.first_name and user.last_name %}
            <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }} </p>
        {% else %}
            <p>Здравствуйте!</p>
        {% endif %}
        <h3>Аватар</h3>
        <img src="{% thumbnail user.image 'scale_high' %}">
        <p>Вы можете изменить аватар в "Управление профилем"->"Изменить данные пользователя"</p>
        <br>
        <div class="qustion-holder">
            {% for question in latest_question_list %}
            <div class="question">
                <a class="question-in" href="{% url 'polls:detail' question.id %}">
                    <h3>{{question.question_header}}</h3>
                    {% if question.image %}
                    <img class="question-img" src="{% thumbnail question.image 'scale_medium' %}">
                    {% endif %}
                    <p>{{question.question_text}}</p>
                </a>
                <a class="question-delete" href="www.example.com">Удалить</a>
        </div>

        {% endfor %}
    </div>
{% else %}
            <p>Вы еще не создали ни одного вопроса</p>
        {% endif %}
        <a class="a-button" href="{% url 'polls:question_create' %}">Создать вопрос</a>
    </div>
    <div>
        <h2>Управление профилем</h2>
        <a class="a-link" href="{% url 'polls:profile_change' %}">Изменить данные пользователя</a>
        <a class="a-link" href="{% url 'polls:password_change' %}">Изменить пароль</a>
        <a class="a-link" href="{% url 'polls:profile_delete' %}">Удалить профиль</a>
    </div>

</div>

    {% comment %} здесь из проекта докинуть вывод вопросов пользователя {% endcomment %}
{% endblock %}

mysite/polls/templates/polls/user/profile_change.html
{% extends "layout/basic.html" %}
{% block title %} Правка личных данных {% endblock %}
{% block content %}
    <h2>Правка личных данных пользователя {{ user.username }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="a-button" type="submit" name="submit">Завершить</button>
    </form>
{% endblock %}

mysite/polls/templates/polls/user/profile_delete.html
{% extends "layout/basic.html" %}
{% block title %} Удаление пользователя {% endblock %}
{% block content %}
    <h2>Удаление пользователя {{ object.username }}</h2>
    <form method="post">
        {% csrf_token %}
        <button class="a-button" name="submit" type="submit">Удалить</button>
    </form>
{% endblock %}

mysite/polls/templates/polls/user/register_user.html
{% extends "layout/basic.html" %}
{% comment %} {% load bootstrap4 %} {% endcomment %}
{% block title %} Регистрация {% endblock %}
{% block content %}
    <h2>Регистрация нового пользователя</h2>
    <form method="post">
    {% csrf_token %}
    {{form}}
    <button class="a-button" type="submit" name="submit">Зарегистрироваться</button>
</form>
{% endblock %}

mysite/polls/templates/polls/user/register_user_success.html
{% extends "layout/basic.html" %}
{% comment %} {% load bootstrap4 %} {% endcomment %}
{% block title %} Регистрация {% endblock %}
{% block content %}
    <h2>Регистрация завершена!</h2>
    <p>Теперь вы можете перейти в свой профиль, чтобы создать там свои опросы, либо вернуться на главную, чтобы голосовать за ответы</p>
    <a class="a-button" href="{% url 'polls:index' %}">На главную</a>
    <a class="a-button" href="{% url 'polls:profile' %}">В профиль</a>
{% endblock %}